displayName: Traefik Real IP
type: middleware
import: github.com/luthfikw/traefik-real-ip-go

summary: When traefik is deployed behind a load balancer, it should get the real IP from the X-Forwarded-For or Cf-Connecting-Ip (if from Cloudflare) header. 

testData:
  IsOnlyCloudflareProxy: false
  excludednets:
    - "1.1.1.1/24"
